const englishWords = [
  { word: 'be', transcription: 'biː', translation: 'быть' },
  { word: 'and', transcription: 'ænd', translation: 'и' },
  { word: 'have', transcription: 'hæv', translation: 'иметь' },
  { word: 'do', transcription: 'duː', translation: 'делать' },
  { word: 'say', transcription: 'seɪ', translation: 'сказать' },
  { word: 'get', transcription: 'ɡɛt', translation: 'получить' },
  { word: 'make', transcription: 'meɪk', translation: 'делать, создавать' },
  { word: 'go', transcription: 'ɡoʊ', translation: 'идти' },
  { word: 'know', transcription: 'noʊ', translation: 'знать' },
  { word: 'take', transcription: 'teɪk', translation: 'брать' },
  { word: 'see', transcription: 'siː', translation: 'видеть' },
  { word: 'come', transcription: 'kʌm', translation: 'приходить' },
  { word: 'think', transcription: 'θɪŋk', translation: 'думать' },
  { word: 'look', transcription: 'lʊk', translation: 'смотреть' },
  { word: 'want', transcription: 'wɑːnt', translation: 'хотеть' },
  { word: 'give', transcription: 'ɡɪv', translation: 'давать' },
  { word: 'use', transcription: 'juːz', translation: 'использовать' },
  { word: 'find', transcription: "faɪnd", translation:'находить'},
  { word:'tell',transcription:'tɛl','translation':'говорить'},
  {word:'ask','transcription':'æsk','translation':'спрашивать'},
  {word:'work','transcription':'wɜrk','translation':'работать'},
  {word:'seem','transcription':'siːm','translation':'казаться'},
  {word:'feel','transcription':'fiːl','translation':'чувствовать'},
  {word:'try','transcription':'traɪ','translation':'пытаться'},
  {word:'leave','transcription':'liːv','translation':'уходить'},
  {word:'call','transcription':'kɔːl','translation':'звонить'},
  {word:'keep','transcription':'kiːp','translation':'держать'},
  {word:'let','transcription':'lɛt','translation':'позволять'},
  {word:'begin','transcription':'bɪˈɡɪn','translation':'начинать'},
  {word:'seem','transcription':'siːm','translation':'казаться'},
  {word:'help','transcription':'hɛlp','translation':'помогать'},
  {word:'talk','transcription':'tɔːk','translation':'говорить'},
  {word:'turn','transcription':'tɜrn','translation':'поворачивать'},
  {word:'start','transcription':'stɑrt','translation':'начинать'},
  {word:'show','transcription':'ʃoʊ','translation':'показывать'},
  {word:'hear','transcription':'hɪr','translation':'слышать'},
  {word:'play','transcription':'pleɪ','translation':'играть'},
  {word:'run','transcription':"rʌn",'translation':"бежать"},
  {word:"move",'transcription':"muːv",'translation':"двигаться"},
  {word:"like",'transcription':"laɪk",'translation':"нравиться"},
  {word:"live",'transcription':"lɪv",'translation':"жить"},
  {word:"believe",'transcription':"bɪˈliːv",'translation':"верить"},
  {word:"hold",'transcription':"hoʊld",'translation':"держать"},
  {word:"bring",'transcription':"brɪŋ",'translation':"приносить"},
  {word:"happen",'transcription':"ˈhæpən",'translation':"случаться"},
  {word:"write",'transcription':"raɪt",'translation':"писать"},
  {word:"provide",'transcription':"prəˈvaɪd",'translation':"предоставлять"},
  {word:"sit",'transcription':"sɪt",'translation':"сидеть"},
  {word:"stand",'transcription':"stænd",'translation':"стоять"},
  {word:"lose",'transcription':"luːz",'translation':"терять"},
  {word:"pay",'transcription':"peɪ",'translation':"платить"},
  {word:"meet",'transcription':"miːt",'translation':"встречать"},
  {word:"include", "transcription": "ɪnˈkluːd", "translation": "включать"},
  {word:"continue", "transcription": "kənˈtɪn.juː", "translation": "продолжать"},
  {word:"set", "transcription": "sɛt", "translation": "устанавливать"},
  {word:"learn", "transcription": "lɜrn", "translation": "учиться"},
  {word:"change", "transcription": "ʧeɪndʒ", "translation": "менять"},
  {word:"lead", "transcription": "li:d", "translation": "вести, руководить"},
  {word:"understand", "transcription": "ʌndər'stænd", "translation": "понимать"},
  {word:"watch", "transcription": "'wɑ:tʃ", "translation": "смотреть (телевизор)"},
  {word:"follow", "transcription": "'fɔloʊ", "translation": "следовать за кем-то или чем-то."},
];

export default englishWords;